### ISSUE TITLE
NameError: uninitialized constant Chef::Handler::Opsmatic::VERSION

### ISSUE THREAD

**Issue by jslusher** [opsmatic/opsmatic-cookbook#10]
The cookbook seems to mostly work, and chef runs complete, but I'm getting this at the end of the run, during the handlers phase (I actually don't know what the chef handler does, and this is the first I've noticed that it exists):

```
Running handlers:
[2015-05-28T08:29:34-07:00] ERROR: Report handler Chef::Handler::Opsmatic raised #<NameError: uninitialized constant Chef::Handler::Opsmatic::VERSION>
[2015-05-28T08:29:34-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-handler-opsmatic-0.0.18/lib/chef/handler/opsmatic.rb:169:in `submit'
[2015-05-28T08:29:34-07:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-handler-opsmatic-0.0.18/lib/chef/handler/opsmatic.rb:75:in `report'
[2015-05-28T08:29:34-07:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler.rb:226:in `run_report_unsafe'
[2015-05-28T08:29:34-07:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler.rb:214:in `run_report_safely'
[2015-05-28T08:29:34-07:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler.rb:93:in `block in run_report_handlers'
[2015-05-28T08:29:34-07:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler.rb:92:in `each'
[2015-05-28T08:29:34-07:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler.rb:92:in `run_report_handlers'
[2015-05-28T08:29:34-07:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler.rb:103:in `block in <class:Handler>'
[2015-05-28T08:29:34-07:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:130:in `call'
[2015-05-28T08:29:34-07:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:130:in `block in run_completed_successfully'
[2015-05-28T08:29:34-07:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:129:in `each'
[2015-05-28T08:29:34-07:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:129:in `run_completed_successfully'
[2015-05-28T08:29:34-07:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:475:in `run'
[2015-05-28T08:29:34-07:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application.rb:271:in `block in fork_chef_client'
[2015-05-28T08:29:34-07:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork'
[2015-05-28T08:29:34-07:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork_chef_client'
[2015-05-28T08:29:34-07:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application.rb:225:in `block in run_chef_client'
[2015-05-28T08:29:34-07:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
[2015-05-28T08:29:34-07:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
[2015-05-28T08:29:34-07:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
[2015-05-28T08:29:34-07:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `loop'
[2015-05-28T08:29:34-07:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `interval_run_chef_client'
[2015-05-28T08:29:34-07:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `run_application'
[2015-05-28T08:29:34-07:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
[2015-05-28T08:29:34-07:00] ERROR: /opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
[2015-05-28T08:29:34-07:00] ERROR: /usr/bin/chef-client:51:in `load'
[2015-05-28T08:29:34-07:00] ERROR: /usr/bin/chef-client:51:in `<main>'
  - Chef::Handler::Opsmatic
Running handlers complete
Chef Client finished, 4/74 resources updated in 6.78713492 seconds
```

**Comment by mihasya** [comment]
@jslusher Thanks for reporting this, I haven't seen that before. Can you also let us know what version of Chef you're using?

@evanjones can you take a look at this when you get a chance? See if you can reproduce..

**Comment by jslusher** [comment]
I get it using both chef 12.2.1 and chef 12.3.

**Comment by mihasya** [comment]
@jslusher we seem to have narrowed down the issue to a version of the `chef_handler` cookbook. Can you do me a favor and run `knife cookbook show chef_handler` and tell me what comes back? if you have version 1.1.9, that is the culprit. We'll start working with the maintainers of that cookbook shortly to figure out what the issue is and if we simply need to change something about our handler to comply with it. In the meantime, if you have version 1.1.9, deleting it and uploading version 1.1.8 should resolve this issue without any functional changes.

**Comment by mihasya** [comment]
Temporary solution to this was to hardcode a dependency for chef_handler <= 1.1.8. Waiting on more comments on https://github.com/opscode-cookbooks/chef_handler/issues/21 for a longer term fix.
