### ISSUE TITLE
Running on ubuntu there is a logic bug, 

### ISSUE THREAD

**Issue by sqorbrody** [opsmatic/opsmatic-cookbook#9]
centos7 is not declared in the global scope and there for when the below code executes 

     Recipe: opsmatic::agent
         * apt_package[opsmatic-agent] action install
           * No candidate version available for opsmatic-agent
           ================================================================================
           Error executing action `install` on resource 'apt_package[opsmatic-agent]'
           ================================================================================
           
           Chef::Exceptions::Package
           -------------------------
           No candidate version available for opsmatic-agent
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/opsmatic/recipes/agent.rb
           
            32: package opsmatic_package do
            33:   action node['opsmatic']['agent_action']
            34:   version node['opsmatic']['agent_version']
            35: end
        36: 
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/opsmatic/recipes/agent.rb:32:in `from_file'
       
           apt_package("opsmatic-agent") do
             action [:install]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             package_name "opsmatic-agent"
             timeout 900
             declared_type :package
             cookbook_name "opsmatic"
             recipe_name "agent"
           end
           
       Recipe: nginx::default
         * service[nginx] action reload
           - reload service service[nginx]
       Recipe: opsmatic::agent
         * service[opsmatic-agent] action restart
           
           ================================================================================
           Error executing action `restart` on resource 'service[opsmatic-agent]'
           ================================================================================
           
           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of /sbin/start opsmatic-agent ----
           STDOUT: 
           STDERR: start: Unknown job: opsmatic-agent
           ---- End output of /sbin/start opsmatic-agent ----
           Ran /sbin/start opsmatic-agent returned 1
       
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/opsmatic/recipes/agent.rb
           
            57: service 'opsmatic-agent' do
        58:   if centos7
            59:     provider Chef::Provider::Service::Systemd
            60:   else
            61:     provider Chef::Provider::Service::Upstart
            62:   end
            63:   action [:enable, :start]
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/opsmatic/recipes/agent.rb:57:in `from_file'
           
           service("opsmatic-agent") do
             provider Chef::Provider::Service::Upstart
             action [:enable, :start]
             supports {:restart=>false, :reload=>false, :status=>false}
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             service_name "opsmatic-agent"
             pattern "opsmatic-agent"
             declared_type :service
             cookbook_name "opsmatic"
             recipe_name "agent"
           end
           
       
       Running handlers:
       [2015-03-23T22:56:21+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-03-23T22:56:21+00:00] ERROR: Exception handlers complete
       [2015-03-23T22:56:21+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       Chef Client failed. 20 resources updated in 41.053728096 seconds
       [2015-03-23T22:56:21+00:00] ERROR: Chef::Exceptions::MultipleFailures
       [2015-03-23T22:56:22+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by sqorbrody** [comment]
This is i386 arch system and you only run on amd_64 ?

**Comment by mihasya** [comment]
Howdy. I believe the centos7 is a red herring, but rerunning kitchen locally on ubuntu 12 and 14 just to be sure. The real issue is likely that yes, the agent packages are only built for 64 bit systems at the moment.  Are you able to get any more debug information out of chef or run `/sbin/start opsmatic-agent` on the machine by hand to see the output?

**Comment by martinisoft** [comment]
I can confirm running into this issue as well. Run list is the `opsmatic::handler` and `opsmatic::agent` then running Chef 11.16.4 on an Ubuntu 14.04.2 (64-bit) system. Further back in the chef run it complains about the apt install with a `The method driver /usr/lib/apt/methods/https could not be found.` error. This led me to install the `apt-transport-https` package. After running chef-client again after re-updating apt manually, the problem corrected itself and all is well for me now. I would add `apt-transport-https` as a package dependency for Ubuntu if you can early on in the chef run.

**Comment by mihasya** [comment]
@martinisoft can you paste the full log please? The agent package does depend explicitly on `apt-transport-https`, but perhaps it's needed earlier in the process. We can certainly fix that. Just for our notes, how was the Ubuntu 14.04.2 box provisioned? (e.g., a particular AWS AMI?)

Thanks for letting us know!

**Comment by mihasya** [comment]
@martinisoft also if you run into any other issues, do ping support@opsmatic.com, it goes to real people very quickly and we're happy to help.

**Comment by martinisoft** [comment]
@mihasya It was provisioned on bare metal with Chef. It might be that apt-transport-https while being a dependency in the package itself is not providing the transport method needed to connect to the package cloud apt repository. You may need to put this into the compile phase as a dependency before apt gets to add it as a repository and attempts to apt-get.

**Comment by martinisoft** [comment]
I'm also seeing the GPG key being declared invalid with the message: `W: GPG error: https://packagecloud.io any InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 37BBEE3F7AD95B3F`
